import { imageSources } from "src/assets/images";

export const notificationList = [
  {
    index: 1,
    message: "class has started.",
    messageHighlight: "Social science",
    time: "08:00AM",
    join: true,
    view: false,
    thumbnail: imageSources.chatDemo1,
  },
  {
    index: 2,
    message: "shared Webinar recording",
    messageHighlight: "Theresa Webb",
    time: "08:00AM",
    join: false,
    view: false,
    thumbnail: imageSources.chatDemo4,
  },
  {
    index: 3,
    message: "shared Webinar recording",
    messageHighlight: "Theresa Webb",
    time: "08:00AM",
    join: false,
    view: false,
    thumbnail: imageSources.chatDemo2,
  },
  {
    index: 4,
    message: "Last day to submit your goals.",
    messageHighlight: "Attention!!",
    time: "23/06/2023, 09:45AM",
    join: false,
    view: false,
    thumbnail: imageSources.chatDemo3,
  },
  {
    index: 5,
    message: "shared Webinar recording",
    messageHighlight: "Theresa Webb",
    time: "08:00AM",
    join: false,
    view: false,
    thumbnail: imageSources.chatDemo6,
  },
  {
    index: 6,
    message: "shared Webinar recording",
    messageHighlight: "Theresa Webb",
    time: "08:00AM",
    join: false,
    view: true,
    thumbnail: imageSources.chatDemo5,
  },
  {
    index: 7,
    message: "shared Webinar recording",
    messageHighlight: "Theresa Webb",
    time: "08:00AM",
    join: false,
    view: false,
    thumbnail: imageSources.chatDemo2,
  },
];
